config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    root to: "homes#top"
    get  'home/about', to: 'homes#about'
    resources :books, only: [:index, :create, :destroy, :update, :edit, :show]
    resources :users, only: [:index,:show, :edit,:update]
#   get '/users/:id'=>'users#show'
#   get '/users/show'=>'users#index'

#   get '/users/:id/edit'=>'users#edit'

#  詳細画面
#   get 'books/:id'=>'books#show'
#   get 'books/:id/edit'=>'books#edit'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, length:{maximum:200}, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy

          validates :name, length:{minimum: 2,maximum:20},uniqueness: true
          validates :introduction,length:{maximum:50}


     has_one_attached :profile_image
         def get_profile_image(width, height)
         unless profile_image.attached?
           file_path = Rails.root.join('app/assets/images/no_image.jpg')
            profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
         end
             profile_image.variant(resize_to_limit:[width, height]).processed
         end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!, except: [:top]
  # before_action :authenticate_user!, except: [:about]
   before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


   protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
      @books = Book.all
      @book= Book.new
      @user = current_user
  end

  def create
     @book = Book.new(book_params)
     @book.user_id = current_user.id
     if  @book.save
      flash[:notice] ="You have created book successfully."
     redirect_to book_path(@book.id)
     else
       @books = Book.all
      @user = current_user
       render :index
     end
  end


  def show
    @book=Book.find(params[:id])
    @book_new=Book.new
    @user=@book.user
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user

  end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  def update
    @book = Book.find(params[:id])
     if @book.update(book_params)
      flash[:notice] ="You have created book successfully."
      redirect_to book_path
     else
       render :edit
     end
  end



private

  def book_params
     params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     before_action :authenticate_user!
     before_action  :ensure_current_user, only:[:edit]

    def new
       @user = User.new
    end

    def create
        user = User.new(list_params)
        user.save
        redirect_to '/users_show'
      # else
          # render :index
      # end
    end

    def show
      @user = User.find(params[:id])
      @book = Book.new
      @books = @user.books
    end

    def index
         @users = User.all
         @user = current_user
         @book=Book.new
    end

    def edit
       @user = User.find(params[:id])
    #   redirect_to(user_path) unless @user == current_user
    end

    def update
          @user = User.find(params[:id])
       if @user.update(user_params)
          flash[:notice] = "You have updated user successfully."
          redirect_to user_path(@user.id)
       else
          render :edit
       end
    end

  private
  # ストロングパラメータ
  def user_params
     params.require(:user).permit(:name, :introduction, :profile_image)
  end

def ensure_current_user
   user = User.find(params[:id])
unless user == current_user
   redirect_to(user_path(current_user.id))
end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>
    <div class="d-grid col-4 mx-auto">
        <h1>Editing Book</h1>


            <% if @book.errors.any? %>
              <%= @book.errors.count %> errors prohibited this obj from being saved:
                  <ul>
                    <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                    <% end %>
                  </ul>
            <% end %>


          <%= form_with model: @book  do |f| %>
             <p>title</p>
              <%= f.text_field :title %>
            <p>Opinion</p>
             <div class="opinion"> <%= f.text_area :body %></div>

              <br>  <%= f.submit 'Update Book', class: "btn btn-success"  %>
               <p id="notice"></p>
                   <br> <%= link_to 'Show', book_path %> | <%= link_to 'Back', books_path %>

          <% end %>


</div>

app/views/books/index.html.erb
<p id="notice"></p>
    <div class='container px-5 px-sm-0'>
       <div class='row'>
         <div class='col-md-3'>

           <% if @book.errors.any? %>
             <%= @book.errors.count %>errors prohibited this obj from being saved:
               <ul>
                  <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
               </ul>
           <% end %>

     <h2>User info</h2>
        <table class='table'>
          <tbody>
            <tr><%= image_tag @user.get_profile_image(100,100) %>
            </tr>
            <tr>
               <th>name</th>
               <th><%= @user.name %></th>
            </tr>
            <tr>
               <th>introduction</th>
               <th><%= @user.introduction %></th>
            </tr>
         </tbody>
        </table>



          <%= link_to  edit_user_path(@user.id), class: "btn btn-outline-dark w-100" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>


              <h2>New book</h2>
                <%= form_with model: @book  do |f| %>
                 <%= f.text_field :title %>
              <h4>Title</h4>
                 <%= f.text_area :body %>
              <h4>Opinion</h4>

                 <br>  <%= f.submit 'Create Book',  class: "btn btn-success"  %>

               <% end %>
         </div>





     <div class='col-md-8 offset-md-1'>
         <h2>Books</h2>
         <table class='table'>

              <thead>
                   <tr>
                      <th colspan="1"></th>
                      <th>Title</th>
                      <th>Opinion</th>
                      <th colspan="3"></th>
                   </tr>
               </thead>

            <showbody>
                 <% @books.each do |book| %>
                     <tr>
                        <td> <%= link_to user_path(book.user) do %>
                             <%= image_tag book.user.get_profile_image(100,100) %>
                             <%#= book.user.name %>
                             <% end %>
                        </td>
                        <td><%= link_to book.title,book_path(book.id) %></td>
                        <td><%= book.body %></td>
                      </tr>


                 <% end %>
            </showbody>


         </table>
     </div>


     </div>
  </div>

app/views/books/show.html.erb
<p id="notice"></p>
   <div class='container px-5 px-sm-0'>
     <div class='row'>
       <div class='col-md-3'>

             <h2>User info</h2>
                 <table class='table'>
                     <tbody>
                         <tr><%= image_tag @user.get_profile_image(100,100)%>
                         </tr>
                         <tr>
                             <th>name</th>
                             <th><%= @user.name %></th>
                         </tr>
                         <tr>
                             <th>introduction</th>
                             <th><%= @user.introduction %></th>
                         </tr>
                     </tbody>
                 </table>


                         <%= link_to  edit_user_path(@user.id), class: "btn btn-outline-dark w-100" do %>
                             <i class="fas fa-user-cog"></i>
                         <% end %>



                 <h2>New book</h2>
                      <%= form_with model: @book_new do |f| %>
                         <h4>Title</h4>
                             <%= f.text_field :title %>
                                 <h4>Opinion</h4>
                                    <%= f.text_area :body %>
                                          <br>  <%= f.submit 'Create Book',  class: "btn btn-success"  %>
                      <% end %>
        </div>


                      <div class='col-md-8 offset-md-1'>
                         <h2>Book detail</h2>

                            <table class='table'>
                              <showbody>
                                 <tr>
                                   <td>
                                       <%= link_to user_path(@book.user.id) do %>
                                           <%= image_tag @book.user.get_profile_image(100,100) %>
                                               <%= @book.user.name %>
                                        <% end %>
                                    </td>
                                      <td><%= @book.title %></td>
                                      <td><%= @book.body %></td>

                                        <% if @user.id == current_user.id%>
                                          <td> <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
                                          <td> <%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に削除しますか？" %></td>
                                        <%end%>
                                 </tr>
                              </showbody>

                             </table>
                      </div>
   </div>
</div>

app/views/homes/_home_list.html.erb
<% book_images.each do |book_image| %>

<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-dark ">
    <div class="container">
      <a class="navbar-brand p-3">Bookers</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown"></div>
      
       <ul class="navbar-nav ml-auto">

            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to 'About', home_about_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "Sine up", home_sign_up_path, class: 'nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", home_sign_in_path, class: 'nav-link text-light' %>
            </li>
<% end %>

app/views/homes/about.html.erb
<p id="notice"></p>
  <div class="text-center">
    <h1>Welcome to <i class="fas fa-book"></i>Bookers!</h1>
  </div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Welcome to <i class="fas fa-book"></i>Bookers!</h1>
        <p>In <i class="fas fa-book"></i>Bookers,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
            <div class="row"><%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %></div>
            <div class="row"><%= link_to 'Sign up', new_user_registration_path, class:  "btn btn-success btn-sm btn-block sign_up"  %></div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-dark ">
        <div class="container">
          <%=link_to "Bookers", root_path,  class: 'nav-link text-light'  %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown"></div>
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

              <li class="nav-item">
                <%= link_to  user_path(current_user.id), class: 'nav-link text-light'  do %>
                  <i class="fas fa-home"></i>Home
                <%end%>
              </li>

              <li class="nav-item">
                <%= link_to  users_path, class: 'nav-link text-light' do%>
                  <i class="fas fa-users"></i>Users
                <%end%>
              </li>

              <li class="nav-item">
                <%= link_to  books_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-book-open"></i>Books
                <%end%>
              </li>

              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt"></i>Log out
                <%end%>
              </li>

            <% else %>

              <li class="nav-item">
                <%= link_to  root_path, class: 'nav-link text-light'  do %>
                  <i class="fas fa-home"></i>Home
                <%end%>
              </li>

              <li class="nav-item">
                <%= link_to  home_about_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-link"></i>About
                <%end%>
              </li>

              <li class="nav-item">
                <%= link_to  new_user_registration_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i>Sign up
                <%end%>
              </li>

              <li class="nav-item">
                <%= link_to  new_user_session_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i>Log in
                <%end%>
              </li>

            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <%= flash[:notice] %>
    <%= yield %>

    <div class="text-center">
      <footer>
        <div style="line-height:100px">
          CopyRight Infratop.inc
        </div>
      </footer>
    </div>

  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>
    <div class="d-grid col-4 mx-auto">
       <h2>User info</h2>

            <%if @user.errors.any? %>
                <%= @user.errors.count %> error prohibited this obj from being saved:
                  <ul>
                    <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
                  </ul>
            <% end %>





          <%= form_with model: @user  do |f| %>
               <p>Name</p>
                <%= f.text_field :name %>

               <p>Image</p>
                <%= f.file_field :profile_image, accept: "image/*" %>

               <p>introduction</p>
                 <div class="introduction"><%= f.text_area :introduction %></div>

                  <br>  <%= f.submit 'Update User', class: "btn btn-secondary"  %>

        <% end %>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>


     <h2>User info</h2>
     <table class='table'>
         <tbody>
         <tr><%= image_tag @user.get_profile_image(100,100) %></tr>
         <tr>
             <th>name</th>
             <th><%= @user.name %></th>
         </tr>
         <tr>
             <th>introduction</th>
             <th><%= @user.introduction %></th>
         </tr>
         </tbody>
         </table>

        <%= link_to  edit_user_path(@user.id), class: "btn btn-outline-dark w-100" do %>
         <i class="fas fa-user-cog"></i>
         <% end %>





        <h2>New book</h2>
          <%= form_with model: @book do |f| %>
              <h4>Title</h4>
              <%= f.text_field :title %>
              <h4>Opinion</h4>
              <%= f.text_area :body %>
              <br>  <%= f.submit 'Create Book',  class: "btn btn-success"  %>
          <% end %>
    </div>




<div class='col-md-8 offset-md-1'>
   <h2>Users</h2>
   <table class='table'>
       <thead>
          <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
          </tr>
       </thead>

       <showbody>
          <% @users.each do |user| %>
          <tr>
          <td><%= image_tag @user.get_profile_image(100,100) %></td>
          <td><div class="name"><%= user.name%></div></td>
          <td><%= link_to 'Show', user_path(user) %></td>
          </tr>
          <% end %>
       </showbody>

       </table>
       </div>



   </div>
   </div>

app/views/users/show.html.erb
<p id="notice"></p>
    <div class='container px-5 px-sm-0'>
      <div class='row'>
            <div class='col-md-3'>



                <h2>User info</h2>
                     <table class='table'>
                      <tbody>
                         <tr><%= image_tag @user.get_profile_image(100,100) %>
                         </tr>
                         <tr>
                            <th>name</th>
                            <th><%= @user.name %></th>
                         </tr>
                          <tr>
                            <th>introduction</th>
                            <th><%= @user.introduction %></th>
                          </tr>
                      </tbody>
                     </table>

                        <%= link_to  edit_user_path(@user.id), class: "btn btn-outline-dark w-100" do %>
                         <i class="fas fa-user-cog"></i>
                         <% end %>



                <h2>New book</h2>
                   <%= form_with model: @book, local:true do |f| %>
                        <h4>Title</h4>
                           <%= f.text_field :title %>
                        <h4>Opinion</h4>
                           <%= f.text_area :body %>

                              <br> <%= f.submit 'Create Book',  class: "btn btn-success"  %>
                  <% end %>
            </div>


                <div class='col-md-8 offset-md-1'>
                   <h2>Books</h2>
                       <table class='table'>
                               <thead>
                                  <tr>
                                      <th colspan="1"></th>
                                      <th>Title</th>
                                      <th>Opinion</th>
                                      <th colspan="3"></th>
                                  </tr>
                               </thead>

                               <showbody>
                                      <% @books.each do |book| %>
                                          <tr>
                                          <td> <%= link_to user_path(book.user) do %>
                                                <%= image_tag book.user.get_profile_image(100,100) %>
                                            　　<%#= book.user.name %>
                                    　         <% end %>
                                          </td>
                                            <td><%= link_to book.title,book_path(book.id) %></td>
                                            <td><%= book.body %></td>
                                            </tr>
                                         <% end %>
                                </showbody>
                       </table>
                   </div>


      </div>
   </div>